### PR TITLE
Fix bugged repeat IDs

### LINKED ISSUE #119: `spatial_buffer_vfold_cv()` should handle `repeats` better
See #115 

spatial_buffer_vfold_cv() can be deterministic (if v is equal to nrow(data), or NULL, or Inf) and we'd probably want to error there as well (although, that's starting to get into the realm of "if you found this edge case, you were doing something weird on purpose")

### PR DESCRIPTION
**Pull request by mikemahoney218**
Addresses #115 (the bug I pointed out in thread, not the core issue).

Fixes #119

### CODE REVIEW

File: R/spatial_vfold_cv.R [hunk 1]
```diff
@@ -230,15 +239,14 @@ posthoc_buffer_rset <- function(data,
...
-    id = names0(length(split_objs), "Fold"),
     v = v
   )
 
   split_objs$splits <- map(split_objs$splits, rm_out, buffer = buffer)
 
   new_rset(
     splits = split_objs$splits,
-    ids = split_objs[, grepl("^id", names(split_objs))],
+    ids = rset[, grepl("^id", names(rset))],
```
Comment (mikemahoney218) [inline R/spatial_vfold_cv.R:249]: @hfrick Is this the best way to grab all the columns, other than `splits`, of an rset object returned by rsample?

This is an internal function, which is taking `rset` straight from an rsample function, so there's no chance a user has renamed columns or anything else.

Comment (hfrick) [reply R/spatial_vfold_cv.R:249]: that looks good to me 👍

**Review by hfrick — APPROVED** [review]
